POST http://localhost:8081/note/postUserNote
Content-Type: application/json 

{    
    "userId" : "123",
    "stationId" : 456[{"Hello World!"}]
}

###
POST http://localhost:8081/user/login
Content-Type: application/json 

{
    "username" : "tochiamanze",
    "password" : "tochi12345"
}

###
POST http://localhost:8081/note/editUserNote
Content-Type: application/json 

{
    "userId" : "123",
    "stationId" : "7890",
    "note" : "Hello world!"
}

###