POST http://localhost:8081/note
Content-Type: application/json 

{    
    "userId" : "123",
    "stationId" : {
        "Orient Heights" : "That station"
    }
}

###
POST http://localhost:8081/note
Content-Type: application/json 

{    
    "userId" : "123",
    "stationId" : {
        "OrientLows" : "little station"
    }
}

###
POST http://localhost:8081/note
Content-Type: application/json 

{    
    "userId" : "123",
    "stationId" : {
        "South Station" : "Clean station"
    }
}

###
PUT http://localhost:8081/note
Content-Type: application/json 

{
    "userId" : "123",
    "stationId" : {
        "OrientLows" : "silly station"
    }
}

###

PUT http://localhost:8081/note
Content-Type: application/json 

{
    "userId" : "123",
    "stationId" : {
        "North Station" : "billy station"
    }
}

###
DELETE http://localhost:8081/note
Content-Type: application/json 

{
    "userId" : "123",
    "stationId" : {
        "Orient Heights" : "That station"
    }
}

###