POST http://localhost:8081/highlight/createHighlight
Content-Type: application/json

{
    "userId": "12315832",
    "lineId": "Blue",
    "stationId": "Orient Heights"
}
###
POST http://localhost:8081/highlight/createHighlight
Content-Type: application/json

{
    "userId": "dude_bro44",
    "lineId": "Blue",
    "stationId": "Orient Heights"
}

### 
GET http://localhost:8081/highlight/getAll?userId=dude_bro44
Content-Type: application/json 

### /deleteAll for testing/demonstration purposes
POST http://localhost:8081/highlight/deleteAll
Content-Type: application/json

### delete by id
POST http://localhost:8081/highlight/delete/66100816d6119c28d66bb3ce
Content-type: application/json

###
PUT http://localhost:8081/highlight/update
Content-Type: application/json

{
    "_id" : "65fc64c34180359a69056c4e",
    "userId": "dude_bro44",
    "lineId": "Orange",
    "stationId": "98765"
}

### get by ID
GET http://localhost:8081/highlight/byId?userId=dude_bro44
Content-Type: application/json

###
POST http://localhost:8081/highlight/createHighlight
Content-Type: application/json

{
    "userId": "TestUser",
    "lineId": "Blue",
    "stationId": "Orient Heights"
}
###