POST http://localhost:8081/favorite
Content-Type: application/json

{
  "userID": "65dcf2711a6692aa2995777e",
  "line": "Red",
  "station": "Alewife"
}

###
GET http://localhost:8081/favorite/getAll
Content-Type: application/json

###
POST http://localhost:8081/favorite/editFavorite
Content-Type: application/json 

{
    "_id" : "65e9ed829ddb8b4c045fcb31",
    "userID" : "65e949535182ee96077b6362",
    "line" : "Green",
    "station" : "North Station"
}


###
POST http://localhost:8081/favorite/deleteAll

###

DELETE http://localhost:8081/favorite/deleteFavorite/6606d8906cc8e9df9da36793
