POST http://localhost:8081/favorite
Content-Type: application/json

{
  "userID": "65e949535182ee96077b6362",
  "line": "Orange",
  "station": "Park Street"
}

###
GET http://localhost:8081/favorite/getAll
Content-Type: application/json

###
POST http://localhost:8081/favorite/editFavorite
Content-Type: application/json 

{
    "_id" : "65e9d8d1dcf0ca799002a398",
    "userID" : "65e949535182ee96077b6362",
    "line" : "Yellow",
    "station" : "East Station"
}


###
POST http://localhost:8081/favorite/deleteAll

###