PUT http://localhost:8081/note
Content-Type: application/json 

{    
    "userId" : "TestUser",
    "stationId" : {
        "South Station" : "1"
    }
}

###
POST http://localhost:8081/note
Content-Type: application/json 

{    
    "userId" : "TestUser",
    "stationId" : {
        "Orient Heights" : "That station"
    }
}

###
POST http://localhost:8081/note
Content-Type: application/json 

{    
    "userId" : "TestUser",
    "stationId" : {
        "OrientLows" : "little station"
    }
}

###
POST http://localhost:8081/note
Content-Type: application/json 

{    
    "userId" : "TestUser",
    "stationId" : {
        "South Station" : "Clean station"
    }
}

###
PUT http://localhost:8081/note
Content-Type: application/json 

{
    "userId" : "TestUser",
    "stationId" : {
        "Central" : "silly station"
    }
}

###
PUT http://localhost:8081/note
Content-Type: application/json 

{
    "userId" :  "dude_bro44"
    "stationId" : {
        "OrientLows" : "janky station"
    }
}

###

PUT http://localhost:8081/note
Content-Type: application/json 

{
    "userId" : "TestUser",
    "stationId" : {
        "North Station" : "billy station"
    }
}

###
PUT http://localhost:8081/note
Content-Type: application/json 

{
    "userId" : "TestUser",
    "stationId" : {
        "South Station" : "billy station"
    }
}

###
DELETE http://localhost:8081/note
Content-Type: application/json 

{
    "userId" : "TestUser",
    "stationId" : {
        "Orient Heights" : "That station"
    }
}

###
GET http://localhost:8081/note/byId/
Content-Type: application/json 

{
    "userId" : "TestUser"    
}

###
GET http://localhost:8081/note/byId/?userId=TestUser
Content-Type: application/json 

###
GET http://localhost:8081/note/byStationId/
Content-Type: application/json 

{
    "userId" : "TestUser",
    "stationId" : "South Station"
}

###